name: YAML Specification
title: null

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  parse_block_html: true

plugins:
- jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
- index.md
- test.md
